name: Build MathBot APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Stáhnout projekt
        uses: actions/checkout@v7

      - name: Nastavit Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Nastavit Java 17
        uses: actions/setup-java@v6
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Nastavit Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: "platform-tools"

      - name: Instalace Buildozeru
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Sestavit APK
        run: |
          buildozer android debug

      - name: Nahrát APK
        uses: actions/upload-artifact@v4
        with:
          name: MathBot-APK
          path: bin/*.apk
